### ISSUE TITLE
Final content toevoegen in index.html

### ISSUE THREAD

**Issue by vdwijngaert** [MakeInBelgium/naaiactie#20]

**Comment by lukin0110** [comment]
Dit is de copy voor het stukje van FOD rechts op de mock-up van Gijs:
Dit patroon en deze werkwijze worden aanbevolen door FOD Volksgezondheid.
Andere patronen die online circuleren zijn niet getest, dus mogelijk niet veilig.
Ook met dit zelfgemaakt mondmasker is het belangrijk altijd de algemene regels te volgen.

**Comment by lukin0110** [comment]
Copy van de intro kunnen jullie hier vinden, die mag erin geplaatst worden! Kan zijn dat er nog minimale aanpassingen volgen morgenvroeg...
MAAK EEN MONDMASKER :mask:
Laat onze zorgverleners niet stikken!
 
Onze zorgverleners hebben je nodig! Om de strijd tegen #COVID19BE te winnen, hebben ze dringend nood aan mondmaskers. Maar die zijn bijna uitgeput. Wij bezorgen hen alvast een back-up plan, met onze zelfgemaakte maskers. Wij laten onze zorgverleners niet stikken. Dat doen wij in hun plaats. Handmade. With love. :heart: 
Ook als je ziek bent en thuis geïsoleerd bent, heb je baat bij zo’n masker. Dit masker verlaagt de kans dat je iemand uit je omgeving besmet. Haal je naaimachines boven en roep je vriend(inn)en op om mee te doen.
#samensterk #tousensemble 
 
Download patroon & werkwijze (edited)

**Comment by lukin0110** [comment]
Onderstaande copy moet komen bij de 9 bollen / gebruiksinstructies. 
DRAAG JE MASKER ZELF, ALS JE ZIEK BENT
Was je handen grondig met water en zeep alvorens het masker aan te raken. Gebruik de uiteinden van de linten om het masker aan te brengen.
Draag het masker alleen wanneer nodig. Bij thuisisolatie bijvoorbeeld, als er anderen in dezelfde ruimte aanwezig zijn.
Hou je ook mét een masker aan de basisregels: handen wassen, voldoende afstand houden en mensen vermijden als je je ziek voelt. 
Zorg dat het masker zo goed mogelijk aansluit op je gezicht. Je moet met mond én neus door het masker ademen. 
Mondmaskers werken minder goed bij kinderen. Verander regelmatig van masker of was het na gebruik op kookprogramma.
Steriliseer elk mondmasker sowieso minstens éénmaal per dag door het te wassen op 90°C.
Gebruik geen elastiekjes om het masker op te houden. Die kan je niet wassen. 
Raak de binnenkant niet aan met je vingers. Als je met 2 kleuren werkt, kun je de binnenkant en de buitenkant van het masker makkelijk herkennen. 
In de omslag van het masker kan je een vervangbare filter schuiven, zoals een stofzuigerzak of een koolstoffilter. Was je handen ook grondig vooraleer je die in het masker stopt.

**Comment by vdwijngaert** [comment]
(moving to final checks issue)
