### ISSUE TITLE
Breng HTML in lijn met NL versie

### ISSUE THREAD

**Issue by lukin0110** [MakeInBelgium/naaiactie#28]
Copy gaat deze nacht in dit document verschijnen

https://docs.google.com/document/d/11Q1Z0HXoxrWScXsv29s3NY_6Ad5bYFG422njeCA8ZbU/edit

De vertaling naar het Frans is grotendeels gedaan door David Candreva en is al gemerged naar `master`. Content zit in `index_fr.html` en kan je al vinden op https://faitesvotremasquebuccal.be/. 

Het belangrijkste dat nog moet gebeuren is de HTML in lijn brengen met de Nederlandstalige versie.

**Comment by lukin0110** [comment]
Update: de PDF versie laat wat op zich wachten. Gaan misschien zelfs niet voor vandaag zijn.

**Comment by pbelmans** [comment]
#66 doet al een deel van de hier opgelijste zaken hoop ik.
