### ISSUE TITLE
Final content check

### ISSUE THREAD

**Issue by vdwijngaert** [MakeInBelgium/naaiactie#30]
Who wants?

## Content nalezen en bevestigen door af te vinken
- [x] sectie 1: "home/concept"
- [x] sectie 2: "doneertips"
- [x] sectie 3: "draagtips"
- [x] sectie 4: "veelgestelde vragen"
- [x] sectie 5: "maaktips"
- [x] sectie 6: "deel en download"

Zie ook https://github.com/MakeInBelgium/naaiactie/issues/20

## Links achter de buttons
- [x] sectie 1: "download patroon" > https://github.com/MakeInBelgium/naaiactie/issues/32
- [x] sectie 4: "naar facebook" > https://github.com/MakeInBelgium/naaiactie/issues/33
- [x] sectie 5: "download patroon & werkwijze"

## Documenten etc
- [x] Checken of de downloadbare bestanden up-to-date zijn en goed linken
- [x] Bestanden ergens plaatsen waar ze niet op een server van ons terecht komen, die load kunnen we wel missen. VB: Google Drive, Github (kan zijn dat cloudflare dat al kan, maar kan zijn dat ze vanaf een bepaalde filesize niet werken)

**Comment by pbelmans** [comment]
Hier enige opmerkingen.

**home/concept**
Is er een link naar een FOD website die approval / meer informatie geeft?

De downloads werken nog niet (maar dat lijkt het doel van #32 te zijn).

**doneertips**
Maak van "Was je handen zo vaak mogelijk. Stop ze in een afsluitbare zak (bv. diepvrieszakjes)." bijvoorbeeld "Was je handen zo vaak mogelijk. Stop de mondmaskers in een afsluitbare zak (bv. diepvrieszakjes)." Of iets in die strekking, maar nu staat er dat je je handen in een afsluitbare zak moet stoppen.

**draagtips**
Tip 5 combineert iets over kinderen met het wassen van de maskers. Misschien het wassen weglaten hier?

**maaktips**
Zijn er een concrete suggesties om je naaimachine steriel te maken?

**Comment by halkmund** [comment]
De copy "maak je naaimachine zo steriel mogelijk" de inhoud geven: "maak je naaimachine zo steriel mogelijk met bv ontsmettingsalcohol of desinfectiegel" maar dan snappier verwoord ...

**Comment by ghost** [comment]
In draagtips punt 5 lijkt het me ook beter "of was het na gebruik op kookprogramma" weg te laten, want dat is precies wat er in punt 6 staat.

**Comment by ghost** [comment]
in maaktips de copy aanpassen naar "maak je naaimachine steriel met ontsmettingsmiddel"

**Comment by ghost** [comment]
in punt 9 van de gebruikstips: copy: "In het masker kan je een vervangbare filter schuiven, zoals een stofzuigerzak of een koolstoffilter. Was je handen grondig voor en na het wisselen van de filter."
