### ISSUE TITLE
Privacy policy & disclaimers

### ISSUE THREAD

**Issue by vdwijngaert** [MakeInBelgium/naaiactie#45]
![image](https://user-images.githubusercontent.com/772137/76945922-870fcf00-6903-11ea-9811-b70e9868196b.png)

**Comment by pbelmans** [comment]
De zin "Dit is geen mondmasker van medische kwaliteit." toevoegen aan

>Dit patroon en deze werkwijze worden aanbevolen door FOD Volksgezondheid.
>Andere patronen die online circuleren zijn niet getest, dus mogelijk niet veilig.
>Ook met dit zelfgemaakt mondmasker is het belangrijk altijd de algemene regels te volgen.

Of zijn er betere suggesties?

**Comment by oenie** [comment]
Ik zou een disclaimer page willen toevoegen:

**Informatie geen vervanging voor medische zorg**

De informatie op deze website is niet bedoeld als vervanging van diensten of informatie van getrainde (medische) professionals en/of zorgverlenende instanties, zoals (huis)artsen, medisch specialisten, spoedeisende hulpverlening, (acute) geestelijke gezondheidszorg, fysiotherapeuten en psychotherapeuten (geen uitputtende opsomming).
De informatie op deze website noch de gebruiksmogelijkheden kunnen gezien worden als een vervanging voor medische of andere professionele hulp, zorg, ondersteuning of informatievoorziening en is niet bedoeld als hulpmiddel bij het stellen van een (zelf-)diagnose.
De informatie is bedoeld als algemene informatie en is niet specifiek gericht op één individueel persoon of één specifieke medische situatie van bijvoorbeeld de bezoeker van de site of iemand in diens omgeving. Dit betekent dat bezoekers aan de informatie geen diagnostische of therapeutische waarde kunnen hechten voor de eigen medische situatie of die van anderen.
In gevallen van ziekten, medische klachten, behandelingen of onderzoek, is de informatie alleen bedoeld als ondersteuning. De informatie op deze website kan in dergelijke situaties dienen als ondersteuning van:
het contact tussen de bezoeker (of diens familielid of andere naasten) en diens therapeut, behandelend arts of andere hulpverlener en
de adviezen die hij/zij van laatstgenoemde ontvangt.
Bezoekers worden aangeraden om medische vragen, klachten of symptomen tijdig voor te leggen aan hun behandelende arts of andere zorgprofessional teneinde professioneel onderzoek, diagnostiek en mogelijk medische zorg te ontvangen. Bezoekers wordt geadviseerd om het tijdig zoeken van professionele zorg nooit uit te stellen of reeds verkregen medisch advies nooit te veronachtzamen op basis van (online) informatie.
Bij acute medische klachten of psychische problemen en bij het verergeren van klachten of symptomen worden bezoekers geadviseerd direct contact op te nemen met hun eigen (huis)arts of het noodnummer.

**‘Zelfzorginformatie’ is geen persoonlijk advies**

In een aantal gevallen bevat de informatie ‘(zelfzorg)adviezen’. Deze ‘adviezen’ betreffen in geen geval direct medisch advies en hebben in geen enkel geval specifieke betrekking op de individuele medische situatie van de bezoeker of iemand waarvoor deze informatie op deze website zoekt.
De zelfzorgadviezen moeten gezien worden als algemene richtlijnen die gelden bij niet-ernstige, veelvoorkomende en alledaagse klachten. Omdat ook bij deze minder ernstige klachten complicaties kunnen voorkomen, is het van belang dat bezoekers bij twijfel en bij aanhoudende of toenemende klachten medisch professionele hulp inroepen.
Ook waar het informatie betreft m.b.t. het gebruik van (zelfzorg) preparaten, betreft het in geen van de gevallen een medisch advies of informatie die specifiek betrekking heeft op de individuele medische situatie van de bezoeker of iemand waarvoor zij/hij informatie op deze website zoekt.

**Medische vragen**
Omdat maakjemondmasker.be in geen geval op directe (bijvoorbeeld telefonisch of via e-mail) of indirecte wijze medische adviezen biedt, die bedoeld zijn als vervanging van professioneel medisch advies, worden geen e-mails van bezoekers beantwoord die betrekking hebben op vragen of verzoeken die bijvoorbeeld ingaan op medische/psychische klachten, de keuze van behandeling of de resultaten van bepaalde (medische) zorg.

**Aansprakelijkheid**
Het gebruik of (doen) toepassen van informatie op maakjemondmasker.be door bezoekers is volledig voor de verantwoordelijkheid en het risico van de gebruiker.
maakjemondmasker.be en diens informatie leveranciers sluiten elke aansprakelijkheid uit voor eventuele schade, directe en indirecte, uit welken hoofde dan ook ontstaan, voortvloeiende uit of verband houdende met het gebruik van of (doen) toepassen van informatie, producten of diensten die worden aangeboden via maakjemondmasker.be, andere websites of bronnen waarnaar binnen/vanuit maakjemondmasker.be wordt verwezen.

**Comment by oenie** [comment]
Da's een default die ik vond ergens, maar lijkt de lading te dekken.
Die ene zin vooraan kan ook al wel helpen als extra.

**Comment by nicovanlooy** [comment]
Let's move on! Ik heb een juriste aangesproken die ons hopelijk kan coachen/nalezen. Kan later ge-update worden.

**Comment by pbelmans** [comment]
Ik kan schijnbaar niet self-assignen (niet genoeg rechten?) maar ik werk er nu aan.
