### ISSUE TITLE
Voeg taalswitcher toe op NL & FR

### ISSUE THREAD

**Issue by lukin0110** [MakeInBelgium/naaiactie#64]
Die voor NL staat al klaar in deze PR: https://github.com/MakeInBelgium/naaiactie/pull/50

Dit stukje HTML moet ook nog toegepast worden in de FR html. Dit kan pas gemerged/toegepast worden op het moment de de FR copy volledig klaar is.

**Comment by pbelmans** [comment]
Zie #66.
